### ISSUE TITLE
No way to specify SSH port in the app.

### ISSUE THREAD

**Issue by AlexanderCurl** [byNeHo/CoD4x-WebAdmin#4]
I am unable to set a different ssh port in the config file, so I unable to create local servers with the app.
I'm using a different ssh port than 22, and can't find any indication in the source to change that

https://github.com/byNeHo/CoD4x-WebAdmin/blob/master/app/controllers/admin/servers.js#L192

```					newServer.saveAsync()
					.then(function(saved) {
						var ssh = new SSH({
							host: config.ssh_access.host,
							user: config.ssh_access.user,
							pass: config.ssh_access.password,
							baseDir: config.cod4_server_plugin.servers_root
```

**Comment by byNeHo** [comment]
try to add manually the port, if it works I will update the code in the next version so that we can change the port in the config files

```
.then(function(saved) {
						var ssh = new SSH({
						host: config.ssh_access.host,
                                                port: 23,
						user: config.ssh_access.user,
						pass: config.ssh_access.password,
						baseDir: config.cod4_server_plugin.servers_root
```

**Comment by AlexanderCurl** [comment]
All right, with this method it doesn't work, but I actually found the simple-ssh node lib, and modified there. It is not included here, because npm pulls it down though installation.
